### ISSUE TITLE
Log segment snapshotting and compacting in data replicas

### ISSUE THREAD

**Issue by evantzhao** [scalog/scalog-old#13]
The current implementation of the log segments in each data replica is never totally flushed to disk -- eventually data replicas will run out of in-memory space to hold the entire structure.

**Comment by ccding** [comment]
https://thehoard.blog/how-kafkas-storage-internals-work-3a29b02e026

Scalog has global sequence numbers, which Kafka doesn't have. There are two ways to implement this. I am not sure which one is better.

We can implement the Kafka storage as the map from local sequence numbers to records, 
(1) with an additional map from global sequence number to records, or
(2) with an additional map from global sequence number to local sequence numbers.

Advantages of (1): more efficient to query by global sequence numbers
Advantages of (2): the additional map can be compressed (represented by cuts?), which uses less storage

The precondition of these two proposals is that, in future, (1) we may want to allow clients to trim individual records (the same as that in Kafka), and (2) we may allow clients to query by local sequence numbers (not sure how it would be used. Probably in implementing Kafka'a API).

**Comment by ghost** [comment]
Please track progress of this issue [here](https://github.com/scalog/scalog/pull/21)

**Comment by ghost** [comment]
Data servers now write records to stable storage with [PR 21: Kafka-based storage system](https://github.com/scalog/scalog/pull/21). However, we still need to free up data servers' in-memory space when appropriate.

**Comment by ghost** [comment]
How about implementing the data servers' in-memory storage like a LRU cache, @ccding ? That is, associating each `Record` with a timestamp when it is initially appended via `Append`, and kicking out the most stale `Record` when the in-memory storage is full. We will need to be careful when setting the size of the in-memory storage such that `Record`s are not over aggressively being kicked out before they are committed.

**Comment by ccding** [comment]
I think we can simply write everything to disk directly, and benefit from OS's cache.

For indexes, as the files are small and losing them doesn't cause safety issues, we can temporarily store them in memory for writes, and load the whole file to memory for reads. If it is too complicated, we can work on this optimization later.
