### ISSUE TITLE
Update Kubernetes Docker Image boot command so that we can build a generic file.

### ISSUE THREAD

**Issue by evantzhao** [scalog/scalog-old#27]
https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/

**Comment by ccding** [comment]
and use the docker image in dockerhub/scalog/scalog:latest

**Comment by evantzhao** [comment]
https://github.com/scalog/scalog-operator/commit/3808b18e9dd9b0c53de52321bfb5996b26071b16
